AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  typescript-aws-lambda-serverless-restapi-kit

  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  RestApiGateway:
    Type: AWS::Serverless::Api # More info about RestApi Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html
    Properties:
      StageName: v1
      CacheClusterEnabled: false
      # CacheClusterSize: '0.5'
      MethodSettings:
        - ResourcePath: /*
          HttpMethod: '*'
          CachingEnabled: true
          CacheTtlInSeconds: 300

  AWSLambdaFunctionPublicAPI:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/handlers/
      Handler: public-api@v1.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        ApiGatewayRoutePostUsers:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users
            Method: POST
            RestApiId:
              Ref: RestApiGateway
        ApiGatewayRouteGetUsers:
          Type: Api
          Properties:
            Path: /users
            Method: GET
            RestApiId:
              Ref: RestApiGateway
        ApiGatewayRouteGetUserById:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: GET
            RestApiId:
              Ref: RestApiGateway
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - public-api@v1.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PublicAPI:
    Description: "API Gateway endpoint URL for v1 stage for PublicAPI function"
    Value: !Sub "https://${RestApiGateway}.execute-api.${AWS::Region}.amazonaws.com/v1/"
  AWSLambdaFunctionPublicAPI:
    Description: "PublicAPI Lambda Function ARN"
    Value: !GetAtt AWSLambdaFunctionPublicAPI.Arn
  AWSLambdaFunctionPublicAPIIamRole:
    Description: "Implicit IAM Role created for PublicAPI function"
    Value: !GetAtt AWSLambdaFunctionPublicAPIRole.Arn
